### PR TITLE
Add real-time vs non-real time to app?

### PR DESCRIPTION
**Pull request by andyg7**
I added a line to the app that says whether the process is scheduled under real-time or non-real-time policy. 

Andy

### CODE REVIEW

**Comment by jaredrummler** [comment]
I would rather not modify Stat as it follows the file format as outlined in the [proc man page](http://man7.org/linux/man-pages/man5/proc.5.html). Thank you for the PR though. This may still be useful info for others in the sample app. 

On Android it may be better to check if [AndroidAppProcess#foreground](https://github.com/jaredrummler/AndroidProcesses/blob/master/library/src/main/java/com/jaredrummler/android/processes/models/AndroidAppProcess.java#L30) is true for the scheduling policy. https://android.googlesource.com/platform/system/core/+/marshmallow-release/libcutils/sched_policy.c

**Comment by andyg7** [comment]
Gotcha makes sense thanks. Will look around and see if I can help out in any other ways - just took an OS course in school where we hacked around in the Linux kernel so would love to make some contributions. 
Thanks again,
Andy

**Comment by andyg7** [comment]
Hi Jared,

Hope all is well. I'm not sure if you remember me but I made a small
contribution to your AndroidProcesses App quite a few months ago. I have a
couple weeks before school starts and was seeing if there was any work or
issues I could work on for your repo?

I had a couple ideas:

1) It seems like the app has per process info, but not info for the system
as a whole; I was thinking it may be helpful if there were information on
the whole system? And potentially rank processes in terms of which ones are
using the CPU, etc most.

2) Right now it has percentage of time in user/kernel mode. Could also add
time spent waiting on I/O.

## Thanks a lot for any feedback,

Andrew Grant
8054482621

**Comment by jaredrummler** [comment]
Thanks for your interest Andrew. I am considering deprecating this project since it will no longer work on Android Nougat. Feel free to fork the project and submit a pull request. The main purpose I wrote this library was just to get a list of running apps, now that doesn't seem possible on Android N without root or using UsageStatsManager (not sure if using UsageStatsManager even does this).

**Pull request closed without merging**
